version: '3'
services:
  audio_db:
    build: 
      context: ./mariadb
      dockerfile: Dockerfile
    image: mariadb
    container_name: daein_mariadb
    restart: always
    environment: 
      - MYSQL_ROOT_PASSWORD=daein
      - TZ=Asia/Seoul
    ports:
      - "15000:3306"
    volumes:
      - ./mariadb/app/db:/var/lib/mysql
      - ./mariadb/app/backup:/backup