FROM python:3.8

WORKDIR /code

COPY app /code/app
COPY config /code/app

WORKDIR /code/app

RUN pip install --no-cache-dir --upgrade -r ./requirements.txt

EXPOSE 8000

RUN chmod +x ./entrypoint.sh

CMD ["./entrypoint.sh"]